variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build
  - test

bitstream:
  stage: build
  image: vivado2018:2018.3
  script:
    - /opt/Xilinx/Vivado/2018.3/bin/vivado -mode tcl -source build.tcl ArtixHwTest.xpr
    - test -f ArtixHwTest.runs/impl_1/*.bit

  artifacts:
    paths:
      - ArtixHwTest.runs/impl_1/*.bit
      - ArtixHwTest.runs/impl_1/runme.log
      - ArtixHwTest.runs/synth_1/runme.log
